version: 0.2

phases:
  pre_build:
    commands:
      - echo Build started on `date`
      - mvn install:install-file -Dfile=ojdbc7-11.2.0.jar -DgroupId=com.oracle -DartifactId=ojdbc7 -Dversion=11.2.0 -Dpackaging=jar
      - aws s3 cp s3://apppropertiesbucket/app.properties src/main/webapp/WEB-INF/Classes/
      - mvn test
  build:
    commands:
      - echo Build completed on `date`
      - mvn clean package
      - mv target/Project-Full-HP-1.0-SNAPSHOT.war Project-Full-HP-1.0-SNAPSHOT.war
      - cd src/main/webapp/WEB-INF/Classes/
      - ls
      - cat app.properties
artifacts:
  files:
    - Project-Full-HP-1.0-SNAPSHOT.war
    - .ebextensions/**